### ISSUE TITLE
Not ideal on scrollable pages

### ISSUE THREAD

**Issue by EmilRais** [Zak-C/ngx-loading#8]
The nature of it being positioned absolute means that if you scroll down, you will scroll under the loading indicator. I use these two global rules to make it super cool:

```css
.backdrop {
    position: fixed !important;
}

.spinner-three-bounce {
    position: fixed !important;
}
```

Now the loading indicator always take up the entire screen and the bouncing dots stay in the middle. It looks super cool - you might want to at least consider that effect. I for one kind of expected it to work like that so others might too.
